CREATE TABLE PRODUCT
(PRODUCT_ID INT,
 NAME STRING,
 CATEGORY1 INT,  
CATEGORY2 INT, 
CATEGORY3 INT)
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ',' 
STORED AS TEXTFILE;

LOAD DATA INPATH   
'/user/ubuntu/product/20150122022500_0.dat' overwrite into table PRODUCT;

SELECT PRODUCT_ID FROM PRODUCT GROUP BY CATEGORY1; 
